### PR TITLE
test for nil/empty Strings

### PR DESCRIPTION
**Pull request by GoFightNguyen**
In addition to creating unit test scenarios for nil and empty `Strings`, I also modified the test for Sort such that there is a test verifying the sort behavior for the output and a test verifying the original input is untouched.

### CODE REVIEW

**Comment by GoFightNguyen** [comment]
Looking at the build log, the failure does not appear related to this PR specifically

**Comment by DylanMeeus** [comment]
Thanks for the PR! 
You're right, the failure is due to testing it on older versions of Go which lack some string functions. But it's not useful to support those older versions of Go anyway. :+1:

**Comment by GoFightNguyen** [comment]
@DylanMeeus do you mind making this repo, or PR, part of hacktoberfest. If you take the PR approach, I also ask you to add it on PRs 100 and 101

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by DylanMeeus** [comment]
@GoFightNguyen  sure, no problem!
 I've added it to the repository itself which should do it :+1:

**Pull request merged**
